repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff-check
      - id: ruff-format
        args: ["--check"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        additional_dependencies:
          - 'numpy'
          - 'types-PyYAML'
          - 'types-python-dateutil'
          - 'types-requests'
          - 'types-setuptools'
          - 'types-frozendict'
          - 'types-redis'
          - 'types-pytz'
          - 'types-Markdown'
