# PKCS number -> RFC definition; unmapped numbers go to Wikipedia overview
PKCS_RFC = {
    1: 8017,
    3: 2631,
    5: 8018,
    7: 2315,
    8: 5958,
    9: 2985,
    10: 2986,
    11: 7512,
    12: 7292,
}

JAVACARD_PACKAGES = [
    "java.io",
    "java.lang",
    "java.rmi",
    "javacard.framework",
    "javacard.framework.service",
    "javacard.security",
    "javacardx.annotations",
    "javacardx.apdu",
    "javacardx.apdu.util",
    "javacardx.biometry",
    "javacardx.biometry1toN",
    "javacardx.crypto",
    "javacardx.external",
    "javacardx.framework.event",
    "javacardx.framework.math",
    "javacardx.framework.nio",
    "javacardx.framework.string",
    "javacardx.framework.time",
    "javacardx.framework.tlv",
    "javacardx.framework.util",
    "javacardx.framework.util.intx",
    "javacardx.security",
    "javacardx.security.bdh",
    "javacardx.security.cert",
    "javacardx.security.derivation",
    "javacardx.security.util",
]
JAVACARD_PACKAGES_LOOKUP = {name.lower(): name for name in JAVACARD_PACKAGES}

# CC long name
CC_CLASSES = {
    "ACE": "PP Module conformance",
    "ACM": "Configuration management",
    "ACO": "Composition",
    "ADO": "Delivery and operation",
    "ADV": "Development",
    "AGD": "Guidance documents",
    "ALC": "Life-cycle support",
    "APE": "Protection Profile evaluation",
    "ASE": "Security Target evaluation",
    "ATE": "Tests",
    "AVA": "Vulnerability assessment",
    "FAU": "Security audit",
    "FCO": "Communication",
    "FCS": "Cryptographic support",
    "FDP": "User data protection",
    "FIA": "Identification and authentication",
    "FMT": "Security management",
    "FPR": "Privacy",
    "FPT": "Protection of the TSF",
    "FRU": "Resource utilisation",
    "FTA": "TOE access",
    "FTP": "Trusted path/channels",
}
