name: Print package version, build wheel
on:
  push:
  workflow_dispatch:

jobs:
  pypi_release:
    name: Print version and build wheel
    runs-on: ubuntu-latest
    if: github.repository == 'crocs-muni/sec-certs'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install build dependencies
        run: python -m pip install build wheel
      - name: Print version
        run: python setup.py --version
      - name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel
